from setuptools import setup

setup(
    name='superform',
    packages=['superform'],
    include_package_data=True,
    install_requires=[
        'apscheduler',
        'bond',
        'facebook-sdk',
        'feedgen',
        'feedparser',
        'flask',
        'flask-sqlalchemy',
        'google-api-python-client',
        'google_auth_oauthlib',
        'idna>=2.5,<2.8',
        'lxml',
        'oauth2client',
        'pyopenssl',
        'PyRSS2Gen',
        'pytest',
        'pytest-flask',
        'pytest-helpers-namespace',
        'pytest-localserver',
        'python3-linkedin',
        'python3-saml',
        'pytest-selenium',
        'python-twitter',
        'reportlab',
        'requests',
        'requests-mock',
        'rfeed',
        'sqlalchemy',
        'selenium',
        'slackclient'
    ]
)
